server:
  port: 8284
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ewallet
    username: ewallet
    password: ewallet
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    hibernate:
      ddl-auto: create

#logging:
#  config: classpath:logback-dev.xml